### ISSUE TITLE
Steps to get node-gyp working on Windows 10

### ISSUE THREAD

**Issue by traceyt** [thaliproject/postcardapp#26]
I tried quite a few things but in the end this set of steps seemed to work for me.

http://stackoverflow.com/a/27385865 

I do have VS2015 installed but it seemed like I needed to install VS2013 desktop edition as well.  Then I followed the steps from the above stackoverflow post.

**Comment by yaronyg** [comment]
Are you sure that you have to use `npm install -msvs_version=2013`? I ask because that is the only difference between our current instructions (taken directly from the node-gyp website) and the link you gave. I asked Srikanth, who is building on windows and he said that he doesn't have to use that option. Can you see what happens if you omit that option?

**Comment by yaronyg** [comment]
Eek! @srichal just pointed out that I'm clueless! You need the switch because you have multiple versions of VS installed and you have to tell npm which one to use. Sigh.... makes sense. I'll update the docs.

**Comment by yaronyg** [comment]
The instructions are now updated.
