### ISSUE TITLE
Building Cordova app gives error regarding min sdk version

### ISSUE THREAD

**Issue by traceyt** [thaliproject/postcardapp#28]
Below is the failure I got.  I edited the androidmanifest.xml file and changed the min version to 16 to get around this.  I am not sure what the correct way to fix this is.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':processDebugManifest'.
  
  > Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than vers
  > ion 16 declared in library [org.thaliproject.p2p.btconnectorlib:btconnectorlib2:
  > 0.0.0] C:\gitRepo\ThaliTest\thali\postcardapp-story_0\platforms\android\build\in
  > termediates\exploded-aar\org.thaliproject.p2p.btconnectorlib\btconnectorlib2\0.0
  > .0\AndroidManifest.xml
  >     Suggestion: use tools:overrideLibrary="org.thaliproject.p2p.btconnectorl
  > ib" to force usage
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

**Comment by yaronyg** [comment]
Sigh.... it turns out that 17 days ago Cordova update their minsdk from 10 to 14. This breaks us because our current install script (see [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/91a810ea142aeea2ced7175d5a35100542ccff50/scripts/androidAfterPrepare.js#L19)) assumes that the minsdk is 10. Now it isn't. So the script silently fails. :(

The whole way we handled this just sucks. We are using an exact string match which is never a smart move. What we actually need to do is to use a XML parser. 

@sreesharp can you please fix this right? The best possibility is to use the features in Cordova that allow us to set the minsdk via a Cordova command. I tried one of them and it didn't work, I think you ran into the same problem that it produced two minSDks rather than replacing the old one. But if you can find another way to do this with a Cordova command that would be idea. If that fails then can you please go find a real XML parser/streamer that can read in the androidManifest file, find the minsdk attribute (regardless of value), update it to the value we want and then output the result?

This is high priority since it blocks anyone who is trying to use Story 0.

Thanks!
