### ISSUE TITLE
Take a photo!

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/postcardapp#62]
We need to take and store photos

**Comment by deadlyfingers** [comment]
How it might look - 
![postcardapp2-photos](https://cloud.githubusercontent.com/assets/1880480/11120561/83b88bca-8948-11e5-8aeb-fb672e8bc3a8.jpg)

**Comment by yaronyg** [comment]
That is cool! Although I was more excited when I thought you had already implemented it. Took me a second to realize it was a mock. :)

**Comment by deadlyfingers** [comment]
Cordova returns base64 encoded imageData which we can store as a PouchDB attachment - http://pouchdb.com/guides/attachments.html or as a Blob. 
Does anyone have a preference?

**Comment by yaronyg** [comment]
There is no Cordova API that will return a buffer? I suppose that makes sense as the Cordova bridge requires everything to be a string. Sigh.. oh well. From a "helping Thali" perspective it would be best if we stored it as an attachment. This would force us to finally exercise those APIs.

**Comment by deadlyfingers** [comment]
I have small images being saved as an attachment in PouchDB using base64. But having trouble with saving **large** images on PouchDB `413 (Request Entity Too Large)`
- UPDATE: fix `app.use( bodyParser.urlencoded({ extended: true, limit: '10mb' }) );`

**Comment by deadlyfingers** [comment]
**iframe issues:** So I want to call Cordova commands from web app client on the mobile but I reckon I need to do some additional wiring to get working it with JXCore / Express app running inside an iframe... 
Tried to get 'parent' of iframe to get access to Cordova functions but this failed due to different origins 'file://' and 'localhost://'. 

OPTIONS : 
1. **Cross Domain Messaging** - post message event using `parent.postMessage('data','*');` to trigger Cordova function in main window - "index.js" then post message back to iframe to trigger callback. https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
2. Or do we really need to run everything inside an iframe? Potentially we can drop ejs requirement. 
- UPDATE: tried removing iframe but ran into various problems - mostly broken file links so going with option 1 which works
